### ISSUE TITLE
Remove all the compile warnings that are shown when the project is started

### ISSUE THREAD

**Issue by sushantkumar23** [NiftySubs/niftysubs#39]
Lot of warnings are currently shown when the Nifty Subs project is started. Work on fixing and removing them.

**Comment by rishabhkeshan** [comment]
Are we having compile warnings on the hosted website?

**Comment by rishabhkeshan** [comment]
Should only be on local history, that is just a linter warning and can be dealt at the end I believe

**Comment by sushantkumar23** [comment]
Yes! But the compiled warning list is too long and there is a lot of unused code. This would reduce a lot of unnecessary imports and probably even improve the load time and create performance improvements.
